export const ANSWER_SURVEY = 'ANSWER_SURVEY';
export const SELECT_SURVEY = 'SELECT_SURVEY';
export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';
export const PREVIOUS_SECTION = 'PREVIOUS_SECTION';
export const TO_NEXT_SECTION = 'TO_NEXT_SECTION';
export const NEXT_BREAK = 'NEXT_BREAK';
export const BROWSER_PREVIOUS_SECTION = 'BROWSER_PREVIOUS_SECTION';
export const SUBMIT_ANSWERS_CHECKED = 'SUBMIT_ANSWERS_CHECKED';